-- Add columns for encrypted secret key storage and generation tracking
ALTER TABLE public.fee_payer_keys 
ADD COLUMN secret_key_encrypted text,
ADD COLUMN is_generated boolean NOT NULL DEFAULT false;

-- Add comment for clarity
COMMENT ON COLUMN public.fee_payer_keys.secret_key_encrypted IS 'AES-256-GCM encrypted secret key bytes (base64 encoded)';
COMMENT ON COLUMN public.fee_payer_keys.is_generated IS 'True if wallet was generated by the application, false if externally added';